services:
  - type: web
    name: web-parser
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "false"
      - key: NODE_ENV
        value: production