services:
  - type: web
    name: web-parser
    env: node
    buildCommand: apt-get install -y chromium && npm install && npm run build
    startCommand: npm start
    envVars:
      - key: CHROMIUM_PATH
        value: /usr/bin/chromium
      - key: NODE_ENV
        value: production